name: continuous-delivery

on:
  push:
    branches: [main]

jobs:
  semver-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
      - uses: ohpensource/platform-cicd/actions/git/generate-version-and-release-notes@2.12.0.1
        name: semver & changelog
        with:
          user-email: "github-svc@ohpen.com"
          user-name: "GitHub Actions"
          version-prefix: "v"
  tfm-docs:
    needs: semver-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Render terraform docs inside the README.md
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: modules/multi_step
          output-file: README.md
          output-method: inject
          git-push: "true"
          indention: 3
          git-commit-message: "[tfm-docs][skip ci] - updating terraform docs"