name: continuous-integration
on:
  pull_request:
    branches: ["main"]

jobs:
  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ohpensource/platform-cicd/actions/terraform/tfm-validate@2.2.0.0
        name: validate-terraform
        with:
          terraform-folder: "/modules/multi_step"
          use-backend: "false"
  validate-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: aquasecurity/tfsec-action@v1.0.0
        name: analyse-security
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: ohpensource/platform-cicd/actions/git/ensure-conventional-commits@0.6.0.0
        name: Ensure conventional commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF
